services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=filevault'
      - 'POSTGRES_PASSWORD=6f461ba2f195'
      - 'POSTGRES_USER=a7x'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
